apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: config-sync-test-bucket-33ut2352
  namespace: config-control
spec:
  location: us-central1
  uniformBucketLevelAccess: true
